
//input ports
add mapped point modclk modclk -type PI PI
add mapped point clk clk -type PI PI
add mapped point rst rst -type PI PI
add mapped point sclk sclk -type PI PI
add mapped point ss ss -type PI PI
add mapped point mosi mosi -type PI PI

//output ports
add mapped point miso miso -type PO PO
add mapped point dsm_out[4] dsm_out[4] -type PO PO
add mapped point dsm_out[3] dsm_out[3] -type PO PO
add mapped point dsm_out[2] dsm_out[2] -type PO PO
add mapped point dsm_out[1] dsm_out[1] -type PO PO
add mapped point dsm_out[0] dsm_out[0] -type PO PO

//inout ports




//Sequential Pins
add mapped point ckDiv/clk_out/q ckDiv/clk_out_reg/Q -type DFF DFF
add mapped point counter_inst/out[1]/q counter_inst/out_reg[1]/Q -type DFF DFF
add mapped point counter_inst/out[0]/q counter_inst/out_reg[0]/Q -type DFF DFF
add mapped point fifo_inst/count[0]/q fifo_inst/count_reg[0]/Q -type DFF DFF
add mapped point fifo_inst/count[1]/q fifo_inst/count_reg[1]/Q -type DFF DFF
add mapped point fifo_inst/count[2]/q fifo_inst/count_reg[2]/Q -type DFF DFF
add mapped point fifo_inst/count[3]/q fifo_inst/count_reg[3]/Q -type DFF DFF
add mapped point fifo_inst/count[4]/q fifo_inst/count_reg[4]/Q -type DFF DFF
add mapped point fifo_inst/count[5]/q fifo_inst/count_reg[5]/Q -type DFF DFF
add mapped point fifo_inst/count[6]/q fifo_inst/count_reg[6]/Q -type DFF DFF
add mapped point fifo_inst/count[7]/q fifo_inst/count_reg[7]/Q -type DFF DFF
add mapped point fifo_inst/data_out[0]/q fifo_inst/data_out_reg[0]/Q -type DFF DFF
add mapped point fifo_inst/data_out[1]/q fifo_inst/data_out_reg[1]/Q -type DFF DFF
add mapped point fifo_inst/data_out[2]/q fifo_inst/data_out_reg[2]/Q -type DFF DFF
add mapped point fifo_inst/data_out[3]/q fifo_inst/data_out_reg[3]/Q -type DFF DFF
add mapped point fifo_inst/data_out[4]/q fifo_inst/data_out_reg[4]/Q -type DFF DFF
add mapped point fifo_inst/data_out[5]/q fifo_inst/data_out_reg[5]/Q -type DFF DFF
add mapped point fifo_inst/data_out[6]/q fifo_inst/data_out_reg[6]/Q -type DFF DFF
add mapped point fifo_inst/data_out[7]/q fifo_inst/data_out_reg[7]/Q -type DFF DFF
add mapped point fifo_inst/data_out[8]/q fifo_inst/data_out_reg[8]/Q -type DFF DFF
add mapped point fifo_inst/data_out[9]/q fifo_inst/data_out_reg[9]/Q -type DFF DFF
add mapped point fifo_inst/data_out[10]/q fifo_inst/data_out_reg[10]/Q -type DFF DFF
add mapped point fifo_inst/data_out[11]/q fifo_inst/data_out_reg[11]/Q -type DFF DFF
add mapped point fifo_inst/data_out[12]/q fifo_inst/data_out_reg[12]/Q -type DFF DFF
add mapped point fifo_inst/data_out[13]/q fifo_inst/data_out_reg[13]/Q -type DFF DFF
add mapped point fifo_inst/data_valid/q fifo_inst/data_valid_reg/Q -type DFF DFF
add mapped point fifo_inst/fifo[0][0]/q fifo_inst/fifo_reg[0][0]/Q -type DFF DFF
add mapped point fifo_inst/fifo[0][1]/q fifo_inst/fifo_reg[0][1]/Q -type DFF DFF
add mapped point fifo_inst/fifo[0][2]/q fifo_inst/fifo_reg[0][2]/Q -type DFF DFF
add mapped point fifo_inst/fifo[0][3]/q fifo_inst/fifo_reg[0][3]/Q -type DFF DFF
add mapped point fifo_inst/fifo[0][4]/q fifo_inst/fifo_reg[0][4]/Q -type DFF DFF
add mapped point fifo_inst/fifo[0][5]/q fifo_inst/fifo_reg[0][5]/Q -type DFF DFF
add mapped point fifo_inst/fifo[0][6]/q fifo_inst/fifo_reg[0][6]/Q -type DFF DFF
add mapped point fifo_inst/fifo[0][7]/q fifo_inst/fifo_reg[0][7]/Q -type DFF DFF
add mapped point fifo_inst/fifo[0][8]/q fifo_inst/fifo_reg[0][8]/Q -type DFF DFF
add mapped point fifo_inst/fifo[0][9]/q fifo_inst/fifo_reg[0][9]/Q -type DFF DFF
add mapped point fifo_inst/fifo[0][10]/q fifo_inst/fifo_reg[0][10]/Q -type DFF DFF
add mapped point fifo_inst/fifo[0][11]/q fifo_inst/fifo_reg[0][11]/Q -type DFF DFF
add mapped point fifo_inst/fifo[0][12]/q fifo_inst/fifo_reg[0][12]/Q -type DFF DFF
add mapped point fifo_inst/fifo[0][13]/q fifo_inst/fifo_reg[0][13]/Q -type DFF DFF
add mapped point fifo_inst/fifo[1][0]/q fifo_inst/fifo_reg[1][0]/Q -type DFF DFF
add mapped point fifo_inst/fifo[1][1]/q fifo_inst/fifo_reg[1][1]/Q -type DFF DFF
add mapped point fifo_inst/fifo[1][2]/q fifo_inst/fifo_reg[1][2]/Q -type DFF DFF
add mapped point fifo_inst/fifo[1][3]/q fifo_inst/fifo_reg[1][3]/Q -type DFF DFF
add mapped point fifo_inst/fifo[1][4]/q fifo_inst/fifo_reg[1][4]/Q -type DFF DFF
add mapped point fifo_inst/fifo[1][5]/q fifo_inst/fifo_reg[1][5]/Q -type DFF DFF
add mapped point fifo_inst/fifo[1][6]/q fifo_inst/fifo_reg[1][6]/Q -type DFF DFF
add mapped point fifo_inst/fifo[1][7]/q fifo_inst/fifo_reg[1][7]/Q -type DFF DFF
add mapped point fifo_inst/fifo[1][8]/q fifo_inst/fifo_reg[1][8]/Q -type DFF DFF
add mapped point fifo_inst/fifo[1][9]/q fifo_inst/fifo_reg[1][9]/Q -type DFF DFF
add mapped point fifo_inst/fifo[1][10]/q fifo_inst/fifo_reg[1][10]/Q -type DFF DFF
add mapped point fifo_inst/fifo[1][11]/q fifo_inst/fifo_reg[1][11]/Q -type DFF DFF
add mapped point fifo_inst/fifo[1][12]/q fifo_inst/fifo_reg[1][12]/Q -type DFF DFF
add mapped point fifo_inst/fifo[1][13]/q fifo_inst/fifo_reg[1][13]/Q -type DFF DFF
add mapped point fifo_inst/fifo[2][0]/q fifo_inst/fifo_reg[2][0]/Q -type DFF DFF
add mapped point fifo_inst/fifo[2][1]/q fifo_inst/fifo_reg[2][1]/Q -type DFF DFF
add mapped point fifo_inst/fifo[2][2]/q fifo_inst/fifo_reg[2][2]/Q -type DFF DFF
add mapped point fifo_inst/fifo[2][3]/q fifo_inst/fifo_reg[2][3]/Q -type DFF DFF
add mapped point fifo_inst/fifo[2][4]/q fifo_inst/fifo_reg[2][4]/Q -type DFF DFF
add mapped point fifo_inst/fifo[2][5]/q fifo_inst/fifo_reg[2][5]/Q -type DFF DFF
add mapped point fifo_inst/fifo[2][6]/q fifo_inst/fifo_reg[2][6]/Q -type DFF DFF
add mapped point fifo_inst/fifo[2][7]/q fifo_inst/fifo_reg[2][7]/Q -type DFF DFF
add mapped point fifo_inst/fifo[2][8]/q fifo_inst/fifo_reg[2][8]/Q -type DFF DFF
add mapped point fifo_inst/fifo[2][9]/q fifo_inst/fifo_reg[2][9]/Q -type DFF DFF
add mapped point fifo_inst/fifo[2][10]/q fifo_inst/fifo_reg[2][10]/Q -type DFF DFF
add mapped point fifo_inst/fifo[2][11]/q fifo_inst/fifo_reg[2][11]/Q -type DFF DFF
add mapped point fifo_inst/fifo[2][12]/q fifo_inst/fifo_reg[2][12]/Q -type DFF DFF
add mapped point fifo_inst/fifo[2][13]/q fifo_inst/fifo_reg[2][13]/Q -type DFF DFF
add mapped point fifo_inst/fifo[3][0]/q fifo_inst/fifo_reg[3][0]/Q -type DFF DFF
add mapped point fifo_inst/fifo[3][1]/q fifo_inst/fifo_reg[3][1]/Q -type DFF DFF
add mapped point fifo_inst/fifo[3][2]/q fifo_inst/fifo_reg[3][2]/Q -type DFF DFF
add mapped point fifo_inst/fifo[3][3]/q fifo_inst/fifo_reg[3][3]/Q -type DFF DFF
add mapped point fifo_inst/fifo[3][4]/q fifo_inst/fifo_reg[3][4]/Q -type DFF DFF
add mapped point fifo_inst/fifo[3][5]/q fifo_inst/fifo_reg[3][5]/Q -type DFF DFF
add mapped point fifo_inst/fifo[3][6]/q fifo_inst/fifo_reg[3][6]/Q -type DFF DFF
add mapped point fifo_inst/fifo[3][7]/q fifo_inst/fifo_reg[3][7]/Q -type DFF DFF
add mapped point fifo_inst/fifo[3][8]/q fifo_inst/fifo_reg[3][8]/Q -type DFF DFF
add mapped point fifo_inst/fifo[3][9]/q fifo_inst/fifo_reg[3][9]/Q -type DFF DFF
add mapped point fifo_inst/fifo[3][10]/q fifo_inst/fifo_reg[3][10]/Q -type DFF DFF
add mapped point fifo_inst/fifo[3][11]/q fifo_inst/fifo_reg[3][11]/Q -type DFF DFF
add mapped point fifo_inst/fifo[3][12]/q fifo_inst/fifo_reg[3][12]/Q -type DFF DFF
add mapped point fifo_inst/fifo[3][13]/q fifo_inst/fifo_reg[3][13]/Q -type DFF DFF
add mapped point fifo_inst/fifo[4][0]/q fifo_inst/fifo_reg[4][0]/Q -type DFF DFF
add mapped point fifo_inst/fifo[4][1]/q fifo_inst/fifo_reg[4][1]/Q -type DFF DFF
add mapped point fifo_inst/fifo[4][2]/q fifo_inst/fifo_reg[4][2]/Q -type DFF DFF
add mapped point fifo_inst/fifo[4][3]/q fifo_inst/fifo_reg[4][3]/Q -type DFF DFF
add mapped point fifo_inst/fifo[4][4]/q fifo_inst/fifo_reg[4][4]/Q -type DFF DFF
add mapped point fifo_inst/fifo[4][5]/q fifo_inst/fifo_reg[4][5]/Q -type DFF DFF
add mapped point fifo_inst/fifo[4][6]/q fifo_inst/fifo_reg[4][6]/Q -type DFF DFF
add mapped point fifo_inst/fifo[4][7]/q fifo_inst/fifo_reg[4][7]/Q -type DFF DFF
add mapped point fifo_inst/fifo[4][8]/q fifo_inst/fifo_reg[4][8]/Q -type DFF DFF
add mapped point fifo_inst/fifo[4][9]/q fifo_inst/fifo_reg[4][9]/Q -type DFF DFF
add mapped point fifo_inst/fifo[4][10]/q fifo_inst/fifo_reg[4][10]/Q -type DFF DFF
add mapped point fifo_inst/fifo[4][11]/q fifo_inst/fifo_reg[4][11]/Q -type DFF DFF
add mapped point fifo_inst/fifo[4][12]/q fifo_inst/fifo_reg[4][12]/Q -type DFF DFF
add mapped point fifo_inst/fifo[4][13]/q fifo_inst/fifo_reg[4][13]/Q -type DFF DFF
add mapped point fifo_inst/fifo[5][0]/q fifo_inst/fifo_reg[5][0]/Q -type DFF DFF
add mapped point fifo_inst/fifo[5][1]/q fifo_inst/fifo_reg[5][1]/Q -type DFF DFF
add mapped point fifo_inst/fifo[5][2]/q fifo_inst/fifo_reg[5][2]/Q -type DFF DFF
add mapped point fifo_inst/fifo[5][3]/q fifo_inst/fifo_reg[5][3]/Q -type DFF DFF
add mapped point fifo_inst/fifo[5][4]/q fifo_inst/fifo_reg[5][4]/Q -type DFF DFF
add mapped point fifo_inst/fifo[5][5]/q fifo_inst/fifo_reg[5][5]/Q -type DFF DFF
add mapped point fifo_inst/fifo[5][6]/q fifo_inst/fifo_reg[5][6]/Q -type DFF DFF
add mapped point fifo_inst/fifo[5][7]/q fifo_inst/fifo_reg[5][7]/Q -type DFF DFF
add mapped point fifo_inst/fifo[5][8]/q fifo_inst/fifo_reg[5][8]/Q -type DFF DFF
add mapped point fifo_inst/fifo[5][9]/q fifo_inst/fifo_reg[5][9]/Q -type DFF DFF
add mapped point fifo_inst/fifo[5][10]/q fifo_inst/fifo_reg[5][10]/Q -type DFF DFF
add mapped point fifo_inst/fifo[5][11]/q fifo_inst/fifo_reg[5][11]/Q -type DFF DFF
add mapped point fifo_inst/fifo[5][12]/q fifo_inst/fifo_reg[5][12]/Q -type DFF DFF
add mapped point fifo_inst/fifo[5][13]/q fifo_inst/fifo_reg[5][13]/Q -type DFF DFF
add mapped point fifo_inst/fifo[6][0]/q fifo_inst/fifo_reg[6][0]/Q -type DFF DFF
add mapped point fifo_inst/fifo[6][1]/q fifo_inst/fifo_reg[6][1]/Q -type DFF DFF
add mapped point fifo_inst/fifo[6][2]/q fifo_inst/fifo_reg[6][2]/Q -type DFF DFF
add mapped point fifo_inst/fifo[6][3]/q fifo_inst/fifo_reg[6][3]/Q -type DFF DFF
add mapped point fifo_inst/fifo[6][4]/q fifo_inst/fifo_reg[6][4]/Q -type DFF DFF
add mapped point fifo_inst/fifo[6][5]/q fifo_inst/fifo_reg[6][5]/Q -type DFF DFF
add mapped point fifo_inst/fifo[6][6]/q fifo_inst/fifo_reg[6][6]/Q -type DFF DFF
add mapped point fifo_inst/fifo[6][7]/q fifo_inst/fifo_reg[6][7]/Q -type DFF DFF
add mapped point fifo_inst/fifo[6][8]/q fifo_inst/fifo_reg[6][8]/Q -type DFF DFF
add mapped point fifo_inst/fifo[6][9]/q fifo_inst/fifo_reg[6][9]/Q -type DFF DFF
add mapped point fifo_inst/fifo[6][10]/q fifo_inst/fifo_reg[6][10]/Q -type DFF DFF
add mapped point fifo_inst/fifo[6][11]/q fifo_inst/fifo_reg[6][11]/Q -type DFF DFF
add mapped point fifo_inst/fifo[6][12]/q fifo_inst/fifo_reg[6][12]/Q -type DFF DFF
add mapped point fifo_inst/fifo[6][13]/q fifo_inst/fifo_reg[6][13]/Q -type DFF DFF
add mapped point fifo_inst/fifo[7][0]/q fifo_inst/fifo_reg[7][0]/Q -type DFF DFF
add mapped point fifo_inst/fifo[7][1]/q fifo_inst/fifo_reg[7][1]/Q -type DFF DFF
add mapped point fifo_inst/fifo[7][2]/q fifo_inst/fifo_reg[7][2]/Q -type DFF DFF
add mapped point fifo_inst/fifo[7][3]/q fifo_inst/fifo_reg[7][3]/Q -type DFF DFF
add mapped point fifo_inst/fifo[7][4]/q fifo_inst/fifo_reg[7][4]/Q -type DFF DFF
add mapped point fifo_inst/fifo[7][5]/q fifo_inst/fifo_reg[7][5]/Q -type DFF DFF
add mapped point fifo_inst/fifo[7][6]/q fifo_inst/fifo_reg[7][6]/Q -type DFF DFF
add mapped point fifo_inst/fifo[7][7]/q fifo_inst/fifo_reg[7][7]/Q -type DFF DFF
add mapped point fifo_inst/fifo[7][8]/q fifo_inst/fifo_reg[7][8]/Q -type DFF DFF
add mapped point fifo_inst/fifo[7][9]/q fifo_inst/fifo_reg[7][9]/Q -type DFF DFF
add mapped point fifo_inst/fifo[7][10]/q fifo_inst/fifo_reg[7][10]/Q -type DFF DFF
add mapped point fifo_inst/fifo[7][11]/q fifo_inst/fifo_reg[7][11]/Q -type DFF DFF
add mapped point fifo_inst/fifo[7][12]/q fifo_inst/fifo_reg[7][12]/Q -type DFF DFF
add mapped point fifo_inst/fifo[7][13]/q fifo_inst/fifo_reg[7][13]/Q -type DFF DFF
add mapped point fifo_inst/read_ptr[0]/q fifo_inst/read_ptr_reg[0]/Q -type DFF DFF
add mapped point fifo_inst/read_ptr[1]/q fifo_inst/read_ptr_reg[1]/Q -type DFF DFF
add mapped point fifo_inst/read_ptr[2]/q fifo_inst/read_ptr_reg[2]/Q -type DFF DFF
add mapped point fifo_inst/write_ptr[0]/q fifo_inst/write_ptr_reg[0]/Q -type DFF DFF
add mapped point fifo_inst/write_ptr[1]/q fifo_inst/write_ptr_reg[1]/Q -type DFF DFF
add mapped point fifo_inst/write_ptr[2]/q fifo_inst/write_ptr_reg[2]/Q -type DFF DFF
add mapped point fifo_miso_inst/count[0]/q fifo_miso_inst/count_reg[0]/Q -type DFF DFF
add mapped point fifo_miso_inst/count[1]/q fifo_miso_inst/count_reg[1]/Q -type DFF DFF
add mapped point fifo_miso_inst/count[2]/q fifo_miso_inst/count_reg[2]/Q -type DFF DFF
add mapped point fifo_miso_inst/count[3]/q fifo_miso_inst/count_reg[3]/Q -type DFF DFF
add mapped point fifo_miso_inst/count[4]/q fifo_miso_inst/count_reg[4]/Q -type DFF DFF
add mapped point fifo_miso_inst/count[5]/q fifo_miso_inst/count_reg[5]/Q -type DFF DFF
add mapped point fifo_miso_inst/count[6]/q fifo_miso_inst/count_reg[6]/Q -type DFF DFF
add mapped point fifo_miso_inst/count[7]/q fifo_miso_inst/count_reg[7]/Q -type DFF DFF
add mapped point fifo_miso_inst/data_out[0]/q fifo_miso_inst/data_out_reg[0]/Q -type DFF DFF
add mapped point fifo_miso_inst/data_out[1]/q fifo_miso_inst/data_out_reg[1]/Q -type DFF DFF
add mapped point fifo_miso_inst/data_out[2]/q fifo_miso_inst/data_out_reg[2]/Q -type DFF DFF
add mapped point fifo_miso_inst/data_out[3]/q fifo_miso_inst/data_out_reg[3]/Q -type DFF DFF
add mapped point fifo_miso_inst/data_out[4]/q fifo_miso_inst/data_out_reg[4]/Q -type DFF DFF
add mapped point fifo_miso_inst/data_out[5]/q fifo_miso_inst/data_out_reg[5]/Q -type DFF DFF
add mapped point fifo_miso_inst/data_out[6]/q fifo_miso_inst/data_out_reg[6]/Q -type DFF DFF
add mapped point fifo_miso_inst/data_out[7]/q fifo_miso_inst/data_out_reg[7]/Q -type DFF DFF
add mapped point fifo_miso_inst/data_out[8]/q fifo_miso_inst/data_out_reg[8]/Q -type DFF DFF
add mapped point fifo_miso_inst/data_out[9]/q fifo_miso_inst/data_out_reg[9]/Q -type DFF DFF
add mapped point fifo_miso_inst/data_out[10]/q fifo_miso_inst/data_out_reg[10]/Q -type DFF DFF
add mapped point fifo_miso_inst/data_out[11]/q fifo_miso_inst/data_out_reg[11]/Q -type DFF DFF
add mapped point fifo_miso_inst/data_out[12]/q fifo_miso_inst/data_out_reg[12]/Q -type DFF DFF
add mapped point fifo_miso_inst/data_out[13]/q fifo_miso_inst/data_out_reg[13]/Q -type DFF DFF
add mapped point fifo_miso_inst/data_out[14]/q fifo_miso_inst/data_out_reg[14]/Q -type DFF DFF
add mapped point fifo_miso_inst/data_out[15]/q fifo_miso_inst/data_out_reg[15]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[0][0]/q fifo_miso_inst/fifo_reg[0][0]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[0][1]/q fifo_miso_inst/fifo_reg[0][1]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[0][2]/q fifo_miso_inst/fifo_reg[0][2]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[0][3]/q fifo_miso_inst/fifo_reg[0][3]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[0][4]/q fifo_miso_inst/fifo_reg[0][4]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[0][5]/q fifo_miso_inst/fifo_reg[0][5]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[0][6]/q fifo_miso_inst/fifo_reg[0][6]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[0][7]/q fifo_miso_inst/fifo_reg[0][7]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[0][8]/q fifo_miso_inst/fifo_reg[0][8]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[0][9]/q fifo_miso_inst/fifo_reg[0][9]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[0][10]/q fifo_miso_inst/fifo_reg[0][10]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[0][11]/q fifo_miso_inst/fifo_reg[0][11]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[0][12]/q fifo_miso_inst/fifo_reg[0][12]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[0][13]/q fifo_miso_inst/fifo_reg[0][13]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[0][14]/q fifo_miso_inst/fifo_reg[0][14]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[0][15]/q fifo_miso_inst/fifo_reg[0][15]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[0][16]/q fifo_miso_inst/fifo_reg[0][16]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[0][17]/q fifo_miso_inst/fifo_reg[0][17]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[0][18]/q fifo_miso_inst/fifo_reg[0][18]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[0][19]/q fifo_miso_inst/fifo_reg[0][19]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[0][20]/q fifo_miso_inst/fifo_reg[0][20]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[0][21]/q fifo_miso_inst/fifo_reg[0][21]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[0][22]/q fifo_miso_inst/fifo_reg[0][22]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[0][23]/q fifo_miso_inst/fifo_reg[0][23]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[0][24]/q fifo_miso_inst/fifo_reg[0][24]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[0][25]/q fifo_miso_inst/fifo_reg[0][25]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[0][26]/q fifo_miso_inst/fifo_reg[0][26]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[0][27]/q fifo_miso_inst/fifo_reg[0][27]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[0][28]/q fifo_miso_inst/fifo_reg[0][28]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[0][29]/q fifo_miso_inst/fifo_reg[0][29]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[0][30]/q fifo_miso_inst/fifo_reg[0][30]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[0][31]/q fifo_miso_inst/fifo_reg[0][31]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[0][32]/q fifo_miso_inst/fifo_reg[0][32]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[0][33]/q fifo_miso_inst/fifo_reg[0][33]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[0][34]/q fifo_miso_inst/fifo_reg[0][34]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[0][35]/q fifo_miso_inst/fifo_reg[0][35]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[0][36]/q fifo_miso_inst/fifo_reg[0][36]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[0][37]/q fifo_miso_inst/fifo_reg[0][37]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[0][38]/q fifo_miso_inst/fifo_reg[0][38]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[0][39]/q fifo_miso_inst/fifo_reg[0][39]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[0][40]/q fifo_miso_inst/fifo_reg[0][40]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[0][41]/q fifo_miso_inst/fifo_reg[0][41]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[0][42]/q fifo_miso_inst/fifo_reg[0][42]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[1][0]/q fifo_miso_inst/fifo_reg[1][0]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[1][1]/q fifo_miso_inst/fifo_reg[1][1]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[1][2]/q fifo_miso_inst/fifo_reg[1][2]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[1][3]/q fifo_miso_inst/fifo_reg[1][3]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[1][4]/q fifo_miso_inst/fifo_reg[1][4]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[1][5]/q fifo_miso_inst/fifo_reg[1][5]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[1][6]/q fifo_miso_inst/fifo_reg[1][6]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[1][7]/q fifo_miso_inst/fifo_reg[1][7]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[1][8]/q fifo_miso_inst/fifo_reg[1][8]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[1][9]/q fifo_miso_inst/fifo_reg[1][9]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[1][10]/q fifo_miso_inst/fifo_reg[1][10]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[1][11]/q fifo_miso_inst/fifo_reg[1][11]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[1][12]/q fifo_miso_inst/fifo_reg[1][12]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[1][13]/q fifo_miso_inst/fifo_reg[1][13]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[1][14]/q fifo_miso_inst/fifo_reg[1][14]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[1][15]/q fifo_miso_inst/fifo_reg[1][15]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[1][16]/q fifo_miso_inst/fifo_reg[1][16]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[1][17]/q fifo_miso_inst/fifo_reg[1][17]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[1][18]/q fifo_miso_inst/fifo_reg[1][18]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[1][19]/q fifo_miso_inst/fifo_reg[1][19]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[1][20]/q fifo_miso_inst/fifo_reg[1][20]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[1][21]/q fifo_miso_inst/fifo_reg[1][21]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[1][22]/q fifo_miso_inst/fifo_reg[1][22]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[1][23]/q fifo_miso_inst/fifo_reg[1][23]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[1][24]/q fifo_miso_inst/fifo_reg[1][24]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[1][25]/q fifo_miso_inst/fifo_reg[1][25]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[1][26]/q fifo_miso_inst/fifo_reg[1][26]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[1][27]/q fifo_miso_inst/fifo_reg[1][27]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[1][28]/q fifo_miso_inst/fifo_reg[1][28]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[1][29]/q fifo_miso_inst/fifo_reg[1][29]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[1][30]/q fifo_miso_inst/fifo_reg[1][30]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[1][31]/q fifo_miso_inst/fifo_reg[1][31]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[1][32]/q fifo_miso_inst/fifo_reg[1][32]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[1][33]/q fifo_miso_inst/fifo_reg[1][33]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[1][34]/q fifo_miso_inst/fifo_reg[1][34]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[1][35]/q fifo_miso_inst/fifo_reg[1][35]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[1][36]/q fifo_miso_inst/fifo_reg[1][36]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[1][37]/q fifo_miso_inst/fifo_reg[1][37]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[1][38]/q fifo_miso_inst/fifo_reg[1][38]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[1][39]/q fifo_miso_inst/fifo_reg[1][39]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[1][40]/q fifo_miso_inst/fifo_reg[1][40]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[1][41]/q fifo_miso_inst/fifo_reg[1][41]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[1][42]/q fifo_miso_inst/fifo_reg[1][42]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[2][0]/q fifo_miso_inst/fifo_reg[2][0]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[2][1]/q fifo_miso_inst/fifo_reg[2][1]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[2][2]/q fifo_miso_inst/fifo_reg[2][2]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[2][3]/q fifo_miso_inst/fifo_reg[2][3]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[2][4]/q fifo_miso_inst/fifo_reg[2][4]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[2][5]/q fifo_miso_inst/fifo_reg[2][5]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[2][6]/q fifo_miso_inst/fifo_reg[2][6]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[2][7]/q fifo_miso_inst/fifo_reg[2][7]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[2][8]/q fifo_miso_inst/fifo_reg[2][8]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[2][9]/q fifo_miso_inst/fifo_reg[2][9]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[2][10]/q fifo_miso_inst/fifo_reg[2][10]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[2][11]/q fifo_miso_inst/fifo_reg[2][11]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[2][12]/q fifo_miso_inst/fifo_reg[2][12]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[2][13]/q fifo_miso_inst/fifo_reg[2][13]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[2][14]/q fifo_miso_inst/fifo_reg[2][14]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[2][15]/q fifo_miso_inst/fifo_reg[2][15]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[2][16]/q fifo_miso_inst/fifo_reg[2][16]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[2][17]/q fifo_miso_inst/fifo_reg[2][17]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[2][18]/q fifo_miso_inst/fifo_reg[2][18]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[2][19]/q fifo_miso_inst/fifo_reg[2][19]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[2][20]/q fifo_miso_inst/fifo_reg[2][20]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[2][21]/q fifo_miso_inst/fifo_reg[2][21]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[2][22]/q fifo_miso_inst/fifo_reg[2][22]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[2][23]/q fifo_miso_inst/fifo_reg[2][23]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[2][24]/q fifo_miso_inst/fifo_reg[2][24]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[2][25]/q fifo_miso_inst/fifo_reg[2][25]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[2][26]/q fifo_miso_inst/fifo_reg[2][26]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[2][27]/q fifo_miso_inst/fifo_reg[2][27]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[2][28]/q fifo_miso_inst/fifo_reg[2][28]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[2][29]/q fifo_miso_inst/fifo_reg[2][29]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[2][30]/q fifo_miso_inst/fifo_reg[2][30]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[2][31]/q fifo_miso_inst/fifo_reg[2][31]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[2][32]/q fifo_miso_inst/fifo_reg[2][32]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[2][33]/q fifo_miso_inst/fifo_reg[2][33]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[2][34]/q fifo_miso_inst/fifo_reg[2][34]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[2][35]/q fifo_miso_inst/fifo_reg[2][35]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[2][36]/q fifo_miso_inst/fifo_reg[2][36]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[2][37]/q fifo_miso_inst/fifo_reg[2][37]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[2][38]/q fifo_miso_inst/fifo_reg[2][38]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[2][39]/q fifo_miso_inst/fifo_reg[2][39]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[2][40]/q fifo_miso_inst/fifo_reg[2][40]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[2][41]/q fifo_miso_inst/fifo_reg[2][41]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[2][42]/q fifo_miso_inst/fifo_reg[2][42]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[3][0]/q fifo_miso_inst/fifo_reg[3][0]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[3][1]/q fifo_miso_inst/fifo_reg[3][1]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[3][2]/q fifo_miso_inst/fifo_reg[3][2]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[3][3]/q fifo_miso_inst/fifo_reg[3][3]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[3][4]/q fifo_miso_inst/fifo_reg[3][4]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[3][5]/q fifo_miso_inst/fifo_reg[3][5]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[3][6]/q fifo_miso_inst/fifo_reg[3][6]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[3][7]/q fifo_miso_inst/fifo_reg[3][7]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[3][8]/q fifo_miso_inst/fifo_reg[3][8]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[3][9]/q fifo_miso_inst/fifo_reg[3][9]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[3][10]/q fifo_miso_inst/fifo_reg[3][10]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[3][11]/q fifo_miso_inst/fifo_reg[3][11]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[3][12]/q fifo_miso_inst/fifo_reg[3][12]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[3][13]/q fifo_miso_inst/fifo_reg[3][13]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[3][14]/q fifo_miso_inst/fifo_reg[3][14]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[3][15]/q fifo_miso_inst/fifo_reg[3][15]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[3][16]/q fifo_miso_inst/fifo_reg[3][16]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[3][17]/q fifo_miso_inst/fifo_reg[3][17]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[3][18]/q fifo_miso_inst/fifo_reg[3][18]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[3][19]/q fifo_miso_inst/fifo_reg[3][19]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[3][20]/q fifo_miso_inst/fifo_reg[3][20]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[3][21]/q fifo_miso_inst/fifo_reg[3][21]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[3][22]/q fifo_miso_inst/fifo_reg[3][22]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[3][23]/q fifo_miso_inst/fifo_reg[3][23]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[3][24]/q fifo_miso_inst/fifo_reg[3][24]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[3][25]/q fifo_miso_inst/fifo_reg[3][25]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[3][26]/q fifo_miso_inst/fifo_reg[3][26]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[3][27]/q fifo_miso_inst/fifo_reg[3][27]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[3][28]/q fifo_miso_inst/fifo_reg[3][28]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[3][29]/q fifo_miso_inst/fifo_reg[3][29]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[3][30]/q fifo_miso_inst/fifo_reg[3][30]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[3][31]/q fifo_miso_inst/fifo_reg[3][31]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[3][32]/q fifo_miso_inst/fifo_reg[3][32]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[3][33]/q fifo_miso_inst/fifo_reg[3][33]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[3][34]/q fifo_miso_inst/fifo_reg[3][34]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[3][35]/q fifo_miso_inst/fifo_reg[3][35]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[3][36]/q fifo_miso_inst/fifo_reg[3][36]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[3][37]/q fifo_miso_inst/fifo_reg[3][37]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[3][38]/q fifo_miso_inst/fifo_reg[3][38]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[3][39]/q fifo_miso_inst/fifo_reg[3][39]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[3][40]/q fifo_miso_inst/fifo_reg[3][40]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[3][41]/q fifo_miso_inst/fifo_reg[3][41]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[3][42]/q fifo_miso_inst/fifo_reg[3][42]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[4][0]/q fifo_miso_inst/fifo_reg[4][0]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[4][1]/q fifo_miso_inst/fifo_reg[4][1]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[4][2]/q fifo_miso_inst/fifo_reg[4][2]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[4][3]/q fifo_miso_inst/fifo_reg[4][3]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[4][4]/q fifo_miso_inst/fifo_reg[4][4]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[4][5]/q fifo_miso_inst/fifo_reg[4][5]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[4][6]/q fifo_miso_inst/fifo_reg[4][6]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[4][7]/q fifo_miso_inst/fifo_reg[4][7]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[4][8]/q fifo_miso_inst/fifo_reg[4][8]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[4][9]/q fifo_miso_inst/fifo_reg[4][9]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[4][10]/q fifo_miso_inst/fifo_reg[4][10]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[4][11]/q fifo_miso_inst/fifo_reg[4][11]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[4][12]/q fifo_miso_inst/fifo_reg[4][12]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[4][13]/q fifo_miso_inst/fifo_reg[4][13]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[4][14]/q fifo_miso_inst/fifo_reg[4][14]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[4][15]/q fifo_miso_inst/fifo_reg[4][15]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[4][16]/q fifo_miso_inst/fifo_reg[4][16]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[4][17]/q fifo_miso_inst/fifo_reg[4][17]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[4][18]/q fifo_miso_inst/fifo_reg[4][18]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[4][19]/q fifo_miso_inst/fifo_reg[4][19]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[4][20]/q fifo_miso_inst/fifo_reg[4][20]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[4][21]/q fifo_miso_inst/fifo_reg[4][21]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[4][22]/q fifo_miso_inst/fifo_reg[4][22]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[4][23]/q fifo_miso_inst/fifo_reg[4][23]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[4][24]/q fifo_miso_inst/fifo_reg[4][24]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[4][25]/q fifo_miso_inst/fifo_reg[4][25]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[4][26]/q fifo_miso_inst/fifo_reg[4][26]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[4][27]/q fifo_miso_inst/fifo_reg[4][27]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[4][28]/q fifo_miso_inst/fifo_reg[4][28]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[4][29]/q fifo_miso_inst/fifo_reg[4][29]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[4][30]/q fifo_miso_inst/fifo_reg[4][30]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[4][31]/q fifo_miso_inst/fifo_reg[4][31]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[4][32]/q fifo_miso_inst/fifo_reg[4][32]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[4][33]/q fifo_miso_inst/fifo_reg[4][33]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[4][34]/q fifo_miso_inst/fifo_reg[4][34]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[4][35]/q fifo_miso_inst/fifo_reg[4][35]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[4][36]/q fifo_miso_inst/fifo_reg[4][36]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[4][37]/q fifo_miso_inst/fifo_reg[4][37]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[4][38]/q fifo_miso_inst/fifo_reg[4][38]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[4][39]/q fifo_miso_inst/fifo_reg[4][39]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[4][40]/q fifo_miso_inst/fifo_reg[4][40]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[4][41]/q fifo_miso_inst/fifo_reg[4][41]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[4][42]/q fifo_miso_inst/fifo_reg[4][42]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[5][0]/q fifo_miso_inst/fifo_reg[5][0]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[5][1]/q fifo_miso_inst/fifo_reg[5][1]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[5][2]/q fifo_miso_inst/fifo_reg[5][2]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[5][3]/q fifo_miso_inst/fifo_reg[5][3]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[5][4]/q fifo_miso_inst/fifo_reg[5][4]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[5][5]/q fifo_miso_inst/fifo_reg[5][5]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[5][6]/q fifo_miso_inst/fifo_reg[5][6]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[5][7]/q fifo_miso_inst/fifo_reg[5][7]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[5][8]/q fifo_miso_inst/fifo_reg[5][8]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[5][9]/q fifo_miso_inst/fifo_reg[5][9]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[5][10]/q fifo_miso_inst/fifo_reg[5][10]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[5][11]/q fifo_miso_inst/fifo_reg[5][11]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[5][12]/q fifo_miso_inst/fifo_reg[5][12]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[5][13]/q fifo_miso_inst/fifo_reg[5][13]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[5][14]/q fifo_miso_inst/fifo_reg[5][14]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[5][15]/q fifo_miso_inst/fifo_reg[5][15]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[5][16]/q fifo_miso_inst/fifo_reg[5][16]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[5][17]/q fifo_miso_inst/fifo_reg[5][17]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[5][18]/q fifo_miso_inst/fifo_reg[5][18]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[5][19]/q fifo_miso_inst/fifo_reg[5][19]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[5][20]/q fifo_miso_inst/fifo_reg[5][20]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[5][21]/q fifo_miso_inst/fifo_reg[5][21]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[5][22]/q fifo_miso_inst/fifo_reg[5][22]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[5][23]/q fifo_miso_inst/fifo_reg[5][23]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[5][24]/q fifo_miso_inst/fifo_reg[5][24]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[5][25]/q fifo_miso_inst/fifo_reg[5][25]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[5][26]/q fifo_miso_inst/fifo_reg[5][26]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[5][27]/q fifo_miso_inst/fifo_reg[5][27]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[5][28]/q fifo_miso_inst/fifo_reg[5][28]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[5][29]/q fifo_miso_inst/fifo_reg[5][29]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[5][30]/q fifo_miso_inst/fifo_reg[5][30]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[5][31]/q fifo_miso_inst/fifo_reg[5][31]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[5][32]/q fifo_miso_inst/fifo_reg[5][32]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[5][33]/q fifo_miso_inst/fifo_reg[5][33]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[5][34]/q fifo_miso_inst/fifo_reg[5][34]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[5][35]/q fifo_miso_inst/fifo_reg[5][35]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[5][36]/q fifo_miso_inst/fifo_reg[5][36]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[5][37]/q fifo_miso_inst/fifo_reg[5][37]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[5][38]/q fifo_miso_inst/fifo_reg[5][38]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[5][39]/q fifo_miso_inst/fifo_reg[5][39]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[5][40]/q fifo_miso_inst/fifo_reg[5][40]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[5][41]/q fifo_miso_inst/fifo_reg[5][41]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[5][42]/q fifo_miso_inst/fifo_reg[5][42]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[6][0]/q fifo_miso_inst/fifo_reg[6][0]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[6][1]/q fifo_miso_inst/fifo_reg[6][1]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[6][2]/q fifo_miso_inst/fifo_reg[6][2]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[6][3]/q fifo_miso_inst/fifo_reg[6][3]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[6][4]/q fifo_miso_inst/fifo_reg[6][4]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[6][5]/q fifo_miso_inst/fifo_reg[6][5]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[6][6]/q fifo_miso_inst/fifo_reg[6][6]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[6][7]/q fifo_miso_inst/fifo_reg[6][7]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[6][8]/q fifo_miso_inst/fifo_reg[6][8]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[6][9]/q fifo_miso_inst/fifo_reg[6][9]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[6][10]/q fifo_miso_inst/fifo_reg[6][10]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[6][11]/q fifo_miso_inst/fifo_reg[6][11]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[6][12]/q fifo_miso_inst/fifo_reg[6][12]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[6][13]/q fifo_miso_inst/fifo_reg[6][13]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[6][14]/q fifo_miso_inst/fifo_reg[6][14]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[6][15]/q fifo_miso_inst/fifo_reg[6][15]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[6][16]/q fifo_miso_inst/fifo_reg[6][16]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[6][17]/q fifo_miso_inst/fifo_reg[6][17]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[6][18]/q fifo_miso_inst/fifo_reg[6][18]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[6][19]/q fifo_miso_inst/fifo_reg[6][19]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[6][20]/q fifo_miso_inst/fifo_reg[6][20]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[6][21]/q fifo_miso_inst/fifo_reg[6][21]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[6][22]/q fifo_miso_inst/fifo_reg[6][22]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[6][23]/q fifo_miso_inst/fifo_reg[6][23]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[6][24]/q fifo_miso_inst/fifo_reg[6][24]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[6][25]/q fifo_miso_inst/fifo_reg[6][25]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[6][26]/q fifo_miso_inst/fifo_reg[6][26]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[6][27]/q fifo_miso_inst/fifo_reg[6][27]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[6][28]/q fifo_miso_inst/fifo_reg[6][28]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[6][29]/q fifo_miso_inst/fifo_reg[6][29]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[6][30]/q fifo_miso_inst/fifo_reg[6][30]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[6][31]/q fifo_miso_inst/fifo_reg[6][31]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[6][32]/q fifo_miso_inst/fifo_reg[6][32]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[6][33]/q fifo_miso_inst/fifo_reg[6][33]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[6][34]/q fifo_miso_inst/fifo_reg[6][34]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[6][35]/q fifo_miso_inst/fifo_reg[6][35]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[6][36]/q fifo_miso_inst/fifo_reg[6][36]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[6][37]/q fifo_miso_inst/fifo_reg[6][37]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[6][38]/q fifo_miso_inst/fifo_reg[6][38]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[6][39]/q fifo_miso_inst/fifo_reg[6][39]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[6][40]/q fifo_miso_inst/fifo_reg[6][40]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[6][41]/q fifo_miso_inst/fifo_reg[6][41]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[6][42]/q fifo_miso_inst/fifo_reg[6][42]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[7][0]/q fifo_miso_inst/fifo_reg[7][0]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[7][1]/q fifo_miso_inst/fifo_reg[7][1]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[7][2]/q fifo_miso_inst/fifo_reg[7][2]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[7][3]/q fifo_miso_inst/fifo_reg[7][3]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[7][4]/q fifo_miso_inst/fifo_reg[7][4]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[7][5]/q fifo_miso_inst/fifo_reg[7][5]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[7][6]/q fifo_miso_inst/fifo_reg[7][6]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[7][7]/q fifo_miso_inst/fifo_reg[7][7]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[7][8]/q fifo_miso_inst/fifo_reg[7][8]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[7][9]/q fifo_miso_inst/fifo_reg[7][9]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[7][10]/q fifo_miso_inst/fifo_reg[7][10]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[7][11]/q fifo_miso_inst/fifo_reg[7][11]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[7][12]/q fifo_miso_inst/fifo_reg[7][12]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[7][13]/q fifo_miso_inst/fifo_reg[7][13]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[7][14]/q fifo_miso_inst/fifo_reg[7][14]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[7][15]/q fifo_miso_inst/fifo_reg[7][15]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[7][16]/q fifo_miso_inst/fifo_reg[7][16]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[7][17]/q fifo_miso_inst/fifo_reg[7][17]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[7][18]/q fifo_miso_inst/fifo_reg[7][18]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[7][19]/q fifo_miso_inst/fifo_reg[7][19]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[7][20]/q fifo_miso_inst/fifo_reg[7][20]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[7][21]/q fifo_miso_inst/fifo_reg[7][21]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[7][22]/q fifo_miso_inst/fifo_reg[7][22]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[7][23]/q fifo_miso_inst/fifo_reg[7][23]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[7][24]/q fifo_miso_inst/fifo_reg[7][24]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[7][25]/q fifo_miso_inst/fifo_reg[7][25]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[7][26]/q fifo_miso_inst/fifo_reg[7][26]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[7][27]/q fifo_miso_inst/fifo_reg[7][27]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[7][28]/q fifo_miso_inst/fifo_reg[7][28]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[7][29]/q fifo_miso_inst/fifo_reg[7][29]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[7][30]/q fifo_miso_inst/fifo_reg[7][30]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[7][31]/q fifo_miso_inst/fifo_reg[7][31]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[7][32]/q fifo_miso_inst/fifo_reg[7][32]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[7][33]/q fifo_miso_inst/fifo_reg[7][33]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[7][34]/q fifo_miso_inst/fifo_reg[7][34]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[7][35]/q fifo_miso_inst/fifo_reg[7][35]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[7][36]/q fifo_miso_inst/fifo_reg[7][36]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[7][37]/q fifo_miso_inst/fifo_reg[7][37]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[7][38]/q fifo_miso_inst/fifo_reg[7][38]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[7][39]/q fifo_miso_inst/fifo_reg[7][39]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[7][40]/q fifo_miso_inst/fifo_reg[7][40]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[7][41]/q fifo_miso_inst/fifo_reg[7][41]/Q -type DFF DFF
add mapped point fifo_miso_inst/fifo[7][42]/q fifo_miso_inst/fifo_reg[7][42]/Q -type DFF DFF
add mapped point fifo_miso_inst/read_ptr[0]/q fifo_miso_inst/read_ptr_reg[0]/Q -type DFF DFF
add mapped point fifo_miso_inst/read_ptr[1]/q fifo_miso_inst/read_ptr_reg[1]/Q -type DFF DFF
add mapped point fifo_miso_inst/read_ptr[2]/q fifo_miso_inst/read_ptr_reg[2]/Q -type DFF DFF
add mapped point fifo_miso_inst/segment_ptr[0]/q fifo_miso_inst/segment_ptr_reg[0]/Q -type DFF DFF
add mapped point fifo_miso_inst/segment_ptr[1]/q fifo_miso_inst/segment_ptr_reg[1]/Q -type DFF DFF
add mapped point fifo_miso_inst/segment_valid/q fifo_miso_inst/segment_valid_reg/Q -type DFF DFF
add mapped point fifo_miso_inst/write_ptr[0]/q fifo_miso_inst/write_ptr_reg[0]/Q -type DFF DFF
add mapped point fifo_miso_inst/write_ptr[1]/q fifo_miso_inst/write_ptr_reg[1]/Q -type DFF DFF
add mapped point fifo_miso_inst/write_ptr[2]/q fifo_miso_inst/write_ptr_reg[2]/Q -type DFF DFF
add mapped point m_43b_inst/memory[1][9]/q m_43b_inst/memory_reg[1][9]/Q -type DFF DFF
add mapped point m_43b_inst/memory[1][1]/q m_43b_inst/memory_reg[1][1]/Q -type DFF DFF
add mapped point m_43b_inst/memory[1][2]/q m_43b_inst/memory_reg[1][2]/Q -type DFF DFF
add mapped point m_43b_inst/memory[1][3]/q m_43b_inst/memory_reg[1][3]/Q -type DFF DFF
add mapped point m_43b_inst/memory[1][4]/q m_43b_inst/memory_reg[1][4]/Q -type DFF DFF
add mapped point m_43b_inst/memory[1][5]/q m_43b_inst/memory_reg[1][5]/Q -type DFF DFF
add mapped point m_43b_inst/memory[1][6]/q m_43b_inst/memory_reg[1][6]/Q -type DFF DFF
add mapped point m_43b_inst/memory[1][7]/q m_43b_inst/memory_reg[1][7]/Q -type DFF DFF
add mapped point m_43b_inst/memory[1][8]/q m_43b_inst/memory_reg[1][8]/Q -type DFF DFF
add mapped point m_43b_inst/memory[1][0]/q m_43b_inst/memory_reg[1][0]/Q -type DFF DFF
add mapped point m_43b_inst/memory[1][10]/q m_43b_inst/memory_reg[1][10]/Q -type DFF DFF
add mapped point m_43b_inst/memory[1][11]/q m_43b_inst/memory_reg[1][11]/Q -type DFF DFF
add mapped point m_43b_inst/memory[2][0]/q m_43b_inst/memory_reg[2][0]/Q -type DFF DFF
add mapped point m_43b_inst/memory[2][1]/q m_43b_inst/memory_reg[2][1]/Q -type DFF DFF
add mapped point m_43b_inst/memory[2][2]/q m_43b_inst/memory_reg[2][2]/Q -type DFF DFF
add mapped point m_43b_inst/memory[2][3]/q m_43b_inst/memory_reg[2][3]/Q -type DFF DFF
add mapped point m_43b_inst/memory[2][4]/q m_43b_inst/memory_reg[2][4]/Q -type DFF DFF
add mapped point m_43b_inst/memory[2][5]/q m_43b_inst/memory_reg[2][5]/Q -type DFF DFF
add mapped point m_43b_inst/memory[3][3]/q m_43b_inst/memory_reg[3][3]/Q -type DFF DFF
add mapped point m_43b_inst/memory[2][7]/q m_43b_inst/memory_reg[2][7]/Q -type DFF DFF
add mapped point m_43b_inst/memory[2][8]/q m_43b_inst/memory_reg[2][8]/Q -type DFF DFF
add mapped point m_43b_inst/memory[2][9]/q m_43b_inst/memory_reg[2][9]/Q -type DFF DFF
add mapped point m_43b_inst/memory[2][10]/q m_43b_inst/memory_reg[2][10]/Q -type DFF DFF
add mapped point m_43b_inst/memory[2][11]/q m_43b_inst/memory_reg[2][11]/Q -type DFF DFF
add mapped point m_43b_inst/memory[3][0]/q m_43b_inst/memory_reg[3][0]/Q -type DFF DFF
add mapped point m_43b_inst/memory[3][1]/q m_43b_inst/memory_reg[3][1]/Q -type DFF DFF
add mapped point m_43b_inst/memory[3][2]/q m_43b_inst/memory_reg[3][2]/Q -type DFF DFF
add mapped point m_43b_inst/memory[2][6]/q m_43b_inst/memory_reg[2][6]/Q -type DFF DFF
add mapped point m_43b_inst/memory[3][4]/q m_43b_inst/memory_reg[3][4]/Q -type DFF DFF
add mapped point m_43b_inst/memory[3][5]/q m_43b_inst/memory_reg[3][5]/Q -type DFF DFF
add mapped point m_43b_inst/memory[3][6]/q m_43b_inst/memory_reg[3][6]/Q -type DFF DFF
add mapped point m_43b_inst/memory[3][7]/q m_43b_inst/memory_reg[3][7]/Q -type DFF DFF
add mapped point m_43b_inst/memory[3][8]/q m_43b_inst/memory_reg[3][8]/Q -type DFF DFF
add mapped point m_43b_inst/memory[3][9]/q m_43b_inst/memory_reg[3][9]/Q -type DFF DFF
add mapped point m_43b_inst/memory[3][10]/q m_43b_inst/memory_reg[3][10]/Q -type DFF DFF
add mapped point m_43b_inst/memory[3][11]/q m_43b_inst/memory_reg[3][11]/Q -type DFF DFF
add mapped point m_43b_inst/memory[0][2]/q m_43b_inst/memory_reg[0][2]/Q -type DFF DFF
add mapped point m_43b_inst/memory[0][3]/q m_43b_inst/memory_reg[0][3]/Q -type DFF DFF
add mapped point m_43b_inst/memory[0][4]/q m_43b_inst/memory_reg[0][4]/Q -type DFF DFF
add mapped point m_43b_inst/memory[0][0]/q m_43b_inst/memory_reg[0][0]/Q -type DFF DFF
add mapped point m_43b_inst/memory[0][6]/q m_43b_inst/memory_reg[0][6]/Q -type DFF DFF
add mapped point m_43b_inst/memory[0][5]/q m_43b_inst/memory_reg[0][5]/Q -type DFF DFF
add mapped point m_43b_inst/memory[0][1]/q m_43b_inst/memory_reg[0][1]/Q -type DFF DFF
add mapped point m_43b_inst/write_ptr[1]/q m_43b_inst/write_ptr_reg[1]/Q -type DFF DFF
add mapped point m_43b_inst/full/q m_43b_inst/full_reg/Q -type DFF DFF
add mapped point m_43b_inst/data_out[2]/q m_43b_inst/data_out_reg[2]/Q -type DFF DFF
add mapped point m_43b_inst/data_out[38]/q m_43b_inst/data_out_reg[38]/Q -type DFF DFF
add mapped point m_43b_inst/data_out[39]/q m_43b_inst/data_out_reg[39]/Q -type DFF DFF
add mapped point m_43b_inst/data_out[40]/q m_43b_inst/data_out_reg[40]/Q -type DFF DFF
add mapped point m_43b_inst/data_out[13]/q m_43b_inst/data_out_reg[13]/Q -type DFF DFF
add mapped point m_43b_inst/data_out[41]/q m_43b_inst/data_out_reg[41]/Q -type DFF DFF
add mapped point m_43b_inst/data_out[42]/q m_43b_inst/data_out_reg[42]/Q -type DFF DFF
add mapped point m_43b_inst/data_out[14]/q m_43b_inst/data_out_reg[14]/Q -type DFF DFF
add mapped point m_43b_inst/data_out[15]/q m_43b_inst/data_out_reg[15]/Q -type DFF DFF
add mapped point m_43b_inst/data_out[1]/q m_43b_inst/data_out_reg[1]/Q -type DFF DFF
add mapped point m_43b_inst/data_out[16]/q m_43b_inst/data_out_reg[16]/Q -type DFF DFF
add mapped point m_43b_inst/data_out[0]/q m_43b_inst/data_out_reg[0]/Q -type DFF DFF
add mapped point m_43b_inst/data_out[17]/q m_43b_inst/data_out_reg[17]/Q -type DFF DFF
add mapped point m_43b_inst/data_out[18]/q m_43b_inst/data_out_reg[18]/Q -type DFF DFF
add mapped point m_43b_inst/data_out[19]/q m_43b_inst/data_out_reg[19]/Q -type DFF DFF
add mapped point m_43b_inst/data_out[4]/q m_43b_inst/data_out_reg[4]/Q -type DFF DFF
add mapped point m_43b_inst/data_out[3]/q m_43b_inst/data_out_reg[3]/Q -type DFF DFF
add mapped point m_43b_inst/data_out[20]/q m_43b_inst/data_out_reg[20]/Q -type DFF DFF
add mapped point m_43b_inst/data_out[30]/q m_43b_inst/data_out_reg[30]/Q -type DFF DFF
add mapped point m_43b_inst/data_out[21]/q m_43b_inst/data_out_reg[21]/Q -type DFF DFF
add mapped point m_43b_inst/data_out[5]/q m_43b_inst/data_out_reg[5]/Q -type DFF DFF
add mapped point m_43b_inst/data_out[22]/q m_43b_inst/data_out_reg[22]/Q -type DFF DFF
add mapped point m_43b_inst/data_out[26]/q m_43b_inst/data_out_reg[26]/Q -type DFF DFF
add mapped point m_43b_inst/data_out[23]/q m_43b_inst/data_out_reg[23]/Q -type DFF DFF
add mapped point m_43b_inst/data_out[7]/q m_43b_inst/data_out_reg[7]/Q -type DFF DFF
add mapped point m_43b_inst/data_out[25]/q m_43b_inst/data_out_reg[25]/Q -type DFF DFF
add mapped point m_43b_inst/data_out[6]/q m_43b_inst/data_out_reg[6]/Q -type DFF DFF
add mapped point m_43b_inst/data_out[27]/q m_43b_inst/data_out_reg[27]/Q -type DFF DFF
add mapped point m_43b_inst/data_out[28]/q m_43b_inst/data_out_reg[28]/Q -type DFF DFF
add mapped point m_43b_inst/data_out[8]/q m_43b_inst/data_out_reg[8]/Q -type DFF DFF
add mapped point m_43b_inst/data_out[29]/q m_43b_inst/data_out_reg[29]/Q -type DFF DFF
add mapped point m_43b_inst/data_out[31]/q m_43b_inst/data_out_reg[31]/Q -type DFF DFF
add mapped point m_43b_inst/data_out[32]/q m_43b_inst/data_out_reg[32]/Q -type DFF DFF
add mapped point m_43b_inst/data_out[9]/q m_43b_inst/data_out_reg[9]/Q -type DFF DFF
add mapped point m_43b_inst/data_out[10]/q m_43b_inst/data_out_reg[10]/Q -type DFF DFF
add mapped point m_43b_inst/data_out[33]/q m_43b_inst/data_out_reg[33]/Q -type DFF DFF
add mapped point m_43b_inst/data_out[34]/q m_43b_inst/data_out_reg[34]/Q -type DFF DFF
add mapped point m_43b_inst/data_out[11]/q m_43b_inst/data_out_reg[11]/Q -type DFF DFF
add mapped point m_43b_inst/data_out[35]/q m_43b_inst/data_out_reg[35]/Q -type DFF DFF
add mapped point m_43b_inst/data_out[36]/q m_43b_inst/data_out_reg[36]/Q -type DFF DFF
add mapped point m_43b_inst/data_out[12]/q m_43b_inst/data_out_reg[12]/Q -type DFF DFF
add mapped point m_43b_inst/data_out[37]/q m_43b_inst/data_out_reg[37]/Q -type DFF DFF
add mapped point m_43b_inst/data_out[24]/q m_43b_inst/data_out_reg[24]/Q -type DFF DFF
add mapped point m_43b_inst/write_ptr[0]/q m_43b_inst/write_ptr_reg[0]/Q -type DFF DFF
add mapped point m_43b_inst/data_ready/q m_43b_inst/data_ready_reg/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay2_out1[1]/q mash111_inst/Unit_Delay2_out1_reg[1]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay2_out1[4]/q mash111_inst/Unit_Delay2_out1_reg[4]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay2_out1[3]/q mash111_inst/Unit_Delay2_out1_reg[3]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay2_out1[2]/q mash111_inst/Unit_Delay2_out1_reg[2]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay2_out1[5]/q mash111_inst/Unit_Delay2_out1_reg[5]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay2_out1[8]/q mash111_inst/Unit_Delay2_out1_reg[8]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay2_out1[7]/q mash111_inst/Unit_Delay2_out1_reg[7]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay2_out1[6]/q mash111_inst/Unit_Delay2_out1_reg[6]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay2_out1[9]/q mash111_inst/Unit_Delay2_out1_reg[9]/Q -type DFF DFF
add mapped point mash111_inst/Delay1_out1/q mash111_inst/Delay1_out1_reg/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay2_out1[0]/q mash111_inst/Unit_Delay2_out1_reg[0]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay_out1[13]/q mash111_inst/Unit_Delay_out1_reg[13]/Q -type DFF DFF
add mapped point mash111_inst/Delay3_out1[1]/q mash111_inst/Delay3_out1_reg[1]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay_out1[1]/q mash111_inst/Unit_Delay_out1_reg[1]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay_out1[2]/q mash111_inst/Unit_Delay_out1_reg[2]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay_out1[3]/q mash111_inst/Unit_Delay_out1_reg[3]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay_out1[4]/q mash111_inst/Unit_Delay_out1_reg[4]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay_out1[5]/q mash111_inst/Unit_Delay_out1_reg[5]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay_out1[6]/q mash111_inst/Unit_Delay_out1_reg[6]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay_out1[7]/q mash111_inst/Unit_Delay_out1_reg[7]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay_out1[8]/q mash111_inst/Unit_Delay_out1_reg[8]/Q -type DFF DFF
add mapped point mash111_inst/Delay_reg[0][0]/q mash111_inst/Delay_reg_reg[0][0]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay_out1[9]/q mash111_inst/Unit_Delay_out1_reg[9]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay_out1[10]/q mash111_inst/Unit_Delay_out1_reg[10]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay_out1[11]/q mash111_inst/Unit_Delay_out1_reg[11]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay_out1[12]/q mash111_inst/Unit_Delay_out1_reg[12]/Q -type DFF DFF
add mapped point mash111_inst/Delay_reg[0][1]/q mash111_inst/Delay_reg_reg[0][1]/Q -type DFF DFF
add mapped point mash111_inst/Delay2_out1/q mash111_inst/Delay2_out1_reg/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay_out1[14]/q mash111_inst/Unit_Delay_out1_reg[14]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay_out1[15]/q mash111_inst/Unit_Delay_out1_reg[15]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay_out1[16]/q mash111_inst/Unit_Delay_out1_reg[16]/Q -type DFF DFF
add mapped point mash111_inst/Delay_reg[1][1]/q mash111_inst/Delay_reg_reg[1][1]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay1_out1[0]/q mash111_inst/Unit_Delay1_out1_reg[0]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay_out1[17]/q mash111_inst/Unit_Delay_out1_reg[17]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay_out1[18]/q mash111_inst/Unit_Delay_out1_reg[18]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay_out1[19]/q mash111_inst/Unit_Delay_out1_reg[19]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay_out1[20]/q mash111_inst/Unit_Delay_out1_reg[20]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay1_out1[1]/q mash111_inst/Unit_Delay1_out1_reg[1]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay_out1[21]/q mash111_inst/Unit_Delay_out1_reg[21]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay_out1[22]/q mash111_inst/Unit_Delay_out1_reg[22]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay_out1[23]/q mash111_inst/Unit_Delay_out1_reg[23]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay_out1[24]/q mash111_inst/Unit_Delay_out1_reg[24]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay1_out1[2]/q mash111_inst/Unit_Delay1_out1_reg[2]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay1_out1[3]/q mash111_inst/Unit_Delay1_out1_reg[3]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay_out1[31]/q mash111_inst/Unit_Delay_out1_reg[31]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay_out1[32]/q mash111_inst/Unit_Delay_out1_reg[32]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay1_out1[6]/q mash111_inst/Unit_Delay1_out1_reg[6]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay_out1[33]/q mash111_inst/Unit_Delay_out1_reg[33]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay_out1[34]/q mash111_inst/Unit_Delay_out1_reg[34]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay_out1[35]/q mash111_inst/Unit_Delay_out1_reg[35]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay_out1[36]/q mash111_inst/Unit_Delay_out1_reg[36]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay1_out1[7]/q mash111_inst/Unit_Delay1_out1_reg[7]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay_out1[37]/q mash111_inst/Unit_Delay_out1_reg[37]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay_out1[38]/q mash111_inst/Unit_Delay_out1_reg[38]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay1_out1[8]/q mash111_inst/Unit_Delay1_out1_reg[8]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay_out1[39]/q mash111_inst/Unit_Delay_out1_reg[39]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay1_out1[9]/q mash111_inst/Unit_Delay1_out1_reg[9]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay_out1[40]/q mash111_inst/Unit_Delay_out1_reg[40]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay_out1[41]/q mash111_inst/Unit_Delay_out1_reg[41]/Q -type DFF DFF
add mapped point mash111_inst/Delay_reg[1][0]/q mash111_inst/Delay_reg_reg[1][0]/Q -type DFF DFF
add mapped point mash111_inst/Delay3_out1[0]/q mash111_inst/Delay3_out1_reg[0]/Q -type DFF DFF
add mapped point mash111_inst/Delay3_out1[2]/q mash111_inst/Delay3_out1_reg[2]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay_out1[25]/q mash111_inst/Unit_Delay_out1_reg[25]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay_out1[26]/q mash111_inst/Unit_Delay_out1_reg[26]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay_out1[27]/q mash111_inst/Unit_Delay_out1_reg[27]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay_out1[28]/q mash111_inst/Unit_Delay_out1_reg[28]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay1_out1[4]/q mash111_inst/Unit_Delay1_out1_reg[4]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay_out1[29]/q mash111_inst/Unit_Delay_out1_reg[29]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay_out1[30]/q mash111_inst/Unit_Delay_out1_reg[30]/Q -type DFF DFF
add mapped point mash111_inst/Unit_Delay1_out1[5]/q mash111_inst/Unit_Delay1_out1_reg[5]/Q -type DFF DFF
add mapped point reg_bank_inst/data_out[0]/q reg_bank_inst/data_out_reg[0]/Q -type DFF DFF
add mapped point reg_bank_inst/data_out[1]/q reg_bank_inst/data_out_reg[1]/Q -type DFF DFF
add mapped point reg_bank_inst/data_out[2]/q reg_bank_inst/data_out_reg[2]/Q -type DFF DFF
add mapped point reg_bank_inst/data_out[3]/q reg_bank_inst/data_out_reg[3]/Q -type DFF DFF
add mapped point reg_bank_inst/data_out[4]/q reg_bank_inst/data_out_reg[4]/Q -type DFF DFF
add mapped point reg_bank_inst/data_out[5]/q reg_bank_inst/data_out_reg[5]/Q -type DFF DFF
add mapped point reg_bank_inst/data_out[6]/q reg_bank_inst/data_out_reg[6]/Q -type DFF DFF
add mapped point reg_bank_inst/data_out[7]/q reg_bank_inst/data_out_reg[7]/Q -type DFF DFF
add mapped point reg_bank_inst/data_out[8]/q reg_bank_inst/data_out_reg[8]/Q -type DFF DFF
add mapped point reg_bank_inst/data_out[9]/q reg_bank_inst/data_out_reg[9]/Q -type DFF DFF
add mapped point reg_bank_inst/data_out[10]/q reg_bank_inst/data_out_reg[10]/Q -type DFF DFF
add mapped point reg_bank_inst/data_out[11]/q reg_bank_inst/data_out_reg[11]/Q -type DFF DFF
add mapped point reg_bank_inst/data_out[12]/q reg_bank_inst/data_out_reg[12]/Q -type DFF DFF
add mapped point reg_bank_inst/data_out[13]/q reg_bank_inst/data_out_reg[13]/Q -type DFF DFF
add mapped point reg_bank_inst/data_out[14]/q reg_bank_inst/data_out_reg[14]/Q -type DFF DFF
add mapped point reg_bank_inst/data_out[15]/q reg_bank_inst/data_out_reg[15]/Q -type DFF DFF
add mapped point reg_bank_inst/data_out[16]/q reg_bank_inst/data_out_reg[16]/Q -type DFF DFF
add mapped point reg_bank_inst/data_out[17]/q reg_bank_inst/data_out_reg[17]/Q -type DFF DFF
add mapped point reg_bank_inst/data_out[18]/q reg_bank_inst/data_out_reg[18]/Q -type DFF DFF
add mapped point reg_bank_inst/data_out[19]/q reg_bank_inst/data_out_reg[19]/Q -type DFF DFF
add mapped point reg_bank_inst/data_out[20]/q reg_bank_inst/data_out_reg[20]/Q -type DFF DFF
add mapped point reg_bank_inst/data_out[21]/q reg_bank_inst/data_out_reg[21]/Q -type DFF DFF
add mapped point reg_bank_inst/data_out[22]/q reg_bank_inst/data_out_reg[22]/Q -type DFF DFF
add mapped point reg_bank_inst/data_out[23]/q reg_bank_inst/data_out_reg[23]/Q -type DFF DFF
add mapped point reg_bank_inst/data_out[24]/q reg_bank_inst/data_out_reg[24]/Q -type DFF DFF
add mapped point reg_bank_inst/data_out[25]/q reg_bank_inst/data_out_reg[25]/Q -type DFF DFF
add mapped point reg_bank_inst/data_out[26]/q reg_bank_inst/data_out_reg[26]/Q -type DFF DFF
add mapped point reg_bank_inst/data_out[27]/q reg_bank_inst/data_out_reg[27]/Q -type DFF DFF
add mapped point reg_bank_inst/data_out[28]/q reg_bank_inst/data_out_reg[28]/Q -type DFF DFF
add mapped point reg_bank_inst/data_out[29]/q reg_bank_inst/data_out_reg[29]/Q -type DFF DFF
add mapped point reg_bank_inst/data_out[30]/q reg_bank_inst/data_out_reg[30]/Q -type DFF DFF
add mapped point reg_bank_inst/data_out[31]/q reg_bank_inst/data_out_reg[31]/Q -type DFF DFF
add mapped point reg_bank_inst/data_out[32]/q reg_bank_inst/data_out_reg[32]/Q -type DFF DFF
add mapped point reg_bank_inst/data_out[33]/q reg_bank_inst/data_out_reg[33]/Q -type DFF DFF
add mapped point reg_bank_inst/data_out[34]/q reg_bank_inst/data_out_reg[34]/Q -type DFF DFF
add mapped point reg_bank_inst/data_out[35]/q reg_bank_inst/data_out_reg[35]/Q -type DFF DFF
add mapped point reg_bank_inst/data_out[36]/q reg_bank_inst/data_out_reg[36]/Q -type DFF DFF
add mapped point reg_bank_inst/data_out[37]/q reg_bank_inst/data_out_reg[37]/Q -type DFF DFF
add mapped point reg_bank_inst/data_out[38]/q reg_bank_inst/data_out_reg[38]/Q -type DFF DFF
add mapped point reg_bank_inst/data_out[39]/q reg_bank_inst/data_out_reg[39]/Q -type DFF DFF
add mapped point reg_bank_inst/data_out[40]/q reg_bank_inst/data_out_reg[40]/Q -type DFF DFF
add mapped point reg_bank_inst/data_out[41]/q reg_bank_inst/data_out_reg[41]/Q -type DFF DFF
add mapped point reg_bank_inst/data_out[42]/q reg_bank_inst/data_out_reg[42]/Q -type DFF DFF
add mapped point reg_bank_inst/read_data_valid/q reg_bank_inst/read_data_valid_reg/Q -type DFF DFF
add mapped point reg_bank_inst/reg0[0]/q reg_bank_inst/reg0_reg[0]/Q -type DFF DFF
add mapped point reg_bank_inst/reg0[1]/q reg_bank_inst/reg0_reg[1]/Q -type DFF DFF
add mapped point reg_bank_inst/reg0[2]/q reg_bank_inst/reg0_reg[2]/Q -type DFF DFF
add mapped point reg_bank_inst/reg0[3]/q reg_bank_inst/reg0_reg[3]/Q -type DFF DFF
add mapped point reg_bank_inst/reg0[4]/q reg_bank_inst/reg0_reg[4]/Q -type DFF DFF
add mapped point reg_bank_inst/reg0[5]/q reg_bank_inst/reg0_reg[5]/Q -type DFF DFF
add mapped point reg_bank_inst/reg0[6]/q reg_bank_inst/reg0_reg[6]/Q -type DFF DFF
add mapped point reg_bank_inst/reg0[7]/q reg_bank_inst/reg0_reg[7]/Q -type DFF DFF
add mapped point reg_bank_inst/reg0[8]/q reg_bank_inst/reg0_reg[8]/Q -type DFF DFF
add mapped point reg_bank_inst/reg0[9]/q reg_bank_inst/reg0_reg[9]/Q -type DFF DFF
add mapped point reg_bank_inst/reg0[10]/q reg_bank_inst/reg0_reg[10]/Q -type DFF DFF
add mapped point reg_bank_inst/reg0[11]/q reg_bank_inst/reg0_reg[11]/Q -type DFF DFF
add mapped point reg_bank_inst/reg0[12]/q reg_bank_inst/reg0_reg[12]/Q -type DFF DFF
add mapped point reg_bank_inst/reg0[13]/q reg_bank_inst/reg0_reg[13]/Q -type DFF DFF
add mapped point reg_bank_inst/reg0[14]/q reg_bank_inst/reg0_reg[14]/Q -type DFF DFF
add mapped point reg_bank_inst/reg0[15]/q reg_bank_inst/reg0_reg[15]/Q -type DFF DFF
add mapped point reg_bank_inst/reg0[16]/q reg_bank_inst/reg0_reg[16]/Q -type DFF DFF
add mapped point reg_bank_inst/reg0[17]/q reg_bank_inst/reg0_reg[17]/Q -type DFF DFF
add mapped point reg_bank_inst/reg0[18]/q reg_bank_inst/reg0_reg[18]/Q -type DFF DFF
add mapped point reg_bank_inst/reg0[19]/q reg_bank_inst/reg0_reg[19]/Q -type DFF DFF
add mapped point reg_bank_inst/reg0[20]/q reg_bank_inst/reg0_reg[20]/Q -type DFF DFF
add mapped point reg_bank_inst/reg0[21]/q reg_bank_inst/reg0_reg[21]/Q -type DFF DFF
add mapped point reg_bank_inst/reg0[22]/q reg_bank_inst/reg0_reg[22]/Q -type DFF DFF
add mapped point reg_bank_inst/reg0[23]/q reg_bank_inst/reg0_reg[23]/Q -type DFF DFF
add mapped point reg_bank_inst/reg0[24]/q reg_bank_inst/reg0_reg[24]/Q -type DFF DFF
add mapped point reg_bank_inst/reg0[25]/q reg_bank_inst/reg0_reg[25]/Q -type DFF DFF
add mapped point reg_bank_inst/reg0[26]/q reg_bank_inst/reg0_reg[26]/Q -type DFF DFF
add mapped point reg_bank_inst/reg0[27]/q reg_bank_inst/reg0_reg[27]/Q -type DFF DFF
add mapped point reg_bank_inst/reg0[28]/q reg_bank_inst/reg0_reg[28]/Q -type DFF DFF
add mapped point reg_bank_inst/reg0[29]/q reg_bank_inst/reg0_reg[29]/Q -type DFF DFF
add mapped point reg_bank_inst/reg0[30]/q reg_bank_inst/reg0_reg[30]/Q -type DFF DFF
add mapped point reg_bank_inst/reg0[31]/q reg_bank_inst/reg0_reg[31]/Q -type DFF DFF
add mapped point reg_bank_inst/reg0[32]/q reg_bank_inst/reg0_reg[32]/Q -type DFF DFF
add mapped point reg_bank_inst/reg0[33]/q reg_bank_inst/reg0_reg[33]/Q -type DFF DFF
add mapped point reg_bank_inst/reg0[34]/q reg_bank_inst/reg0_reg[34]/Q -type DFF DFF
add mapped point reg_bank_inst/reg0[35]/q reg_bank_inst/reg0_reg[35]/Q -type DFF DFF
add mapped point reg_bank_inst/reg0[36]/q reg_bank_inst/reg0_reg[36]/Q -type DFF DFF
add mapped point reg_bank_inst/reg0[37]/q reg_bank_inst/reg0_reg[37]/Q -type DFF DFF
add mapped point reg_bank_inst/reg0[38]/q reg_bank_inst/reg0_reg[38]/Q -type DFF DFF
add mapped point reg_bank_inst/reg0[39]/q reg_bank_inst/reg0_reg[39]/Q -type DFF DFF
add mapped point reg_bank_inst/reg0[40]/q reg_bank_inst/reg0_reg[40]/Q -type DFF DFF
add mapped point reg_bank_inst/reg0[41]/q reg_bank_inst/reg0_reg[41]/Q -type DFF DFF
add mapped point reg_bank_inst/reg0[42]/q reg_bank_inst/reg0_reg[42]/Q -type DFF DFF
add mapped point reg_bank_inst/reg1[0]/q reg_bank_inst/reg1_reg[0]/Q -type DFF DFF
add mapped point reg_bank_inst/reg1[1]/q reg_bank_inst/reg1_reg[1]/Q -type DFF DFF
add mapped point reg_bank_inst/reg1[2]/q reg_bank_inst/reg1_reg[2]/Q -type DFF DFF
add mapped point reg_bank_inst/reg1[3]/q reg_bank_inst/reg1_reg[3]/Q -type DFF DFF
add mapped point reg_bank_inst/reg1[4]/q reg_bank_inst/reg1_reg[4]/Q -type DFF DFF
add mapped point reg_bank_inst/reg1[5]/q reg_bank_inst/reg1_reg[5]/Q -type DFF DFF
add mapped point reg_bank_inst/reg1[6]/q reg_bank_inst/reg1_reg[6]/Q -type DFF DFF
add mapped point reg_bank_inst/reg1[7]/q reg_bank_inst/reg1_reg[7]/Q -type DFF DFF
add mapped point reg_bank_inst/reg1[8]/q reg_bank_inst/reg1_reg[8]/Q -type DFF DFF
add mapped point reg_bank_inst/reg1[9]/q reg_bank_inst/reg1_reg[9]/Q -type DFF DFF
add mapped point reg_bank_inst/reg1[10]/q reg_bank_inst/reg1_reg[10]/Q -type DFF DFF
add mapped point reg_bank_inst/reg1[11]/q reg_bank_inst/reg1_reg[11]/Q -type DFF DFF
add mapped point reg_bank_inst/reg1[12]/q reg_bank_inst/reg1_reg[12]/Q -type DFF DFF
add mapped point reg_bank_inst/reg1[13]/q reg_bank_inst/reg1_reg[13]/Q -type DFF DFF
add mapped point reg_bank_inst/reg1[14]/q reg_bank_inst/reg1_reg[14]/Q -type DFF DFF
add mapped point reg_bank_inst/reg1[15]/q reg_bank_inst/reg1_reg[15]/Q -type DFF DFF
add mapped point reg_bank_inst/reg1[16]/q reg_bank_inst/reg1_reg[16]/Q -type DFF DFF
add mapped point reg_bank_inst/reg1[17]/q reg_bank_inst/reg1_reg[17]/Q -type DFF DFF
add mapped point reg_bank_inst/reg1[18]/q reg_bank_inst/reg1_reg[18]/Q -type DFF DFF
add mapped point reg_bank_inst/reg1[19]/q reg_bank_inst/reg1_reg[19]/Q -type DFF DFF
add mapped point reg_bank_inst/reg1[20]/q reg_bank_inst/reg1_reg[20]/Q -type DFF DFF
add mapped point reg_bank_inst/reg1[21]/q reg_bank_inst/reg1_reg[21]/Q -type DFF DFF
add mapped point reg_bank_inst/reg1[22]/q reg_bank_inst/reg1_reg[22]/Q -type DFF DFF
add mapped point reg_bank_inst/reg1[23]/q reg_bank_inst/reg1_reg[23]/Q -type DFF DFF
add mapped point reg_bank_inst/reg1[24]/q reg_bank_inst/reg1_reg[24]/Q -type DFF DFF
add mapped point reg_bank_inst/reg1[25]/q reg_bank_inst/reg1_reg[25]/Q -type DFF DFF
add mapped point reg_bank_inst/reg1[26]/q reg_bank_inst/reg1_reg[26]/Q -type DFF DFF
add mapped point reg_bank_inst/reg1[27]/q reg_bank_inst/reg1_reg[27]/Q -type DFF DFF
add mapped point reg_bank_inst/reg1[28]/q reg_bank_inst/reg1_reg[28]/Q -type DFF DFF
add mapped point reg_bank_inst/reg1[29]/q reg_bank_inst/reg1_reg[29]/Q -type DFF DFF
add mapped point reg_bank_inst/reg1[30]/q reg_bank_inst/reg1_reg[30]/Q -type DFF DFF
add mapped point reg_bank_inst/reg1[31]/q reg_bank_inst/reg1_reg[31]/Q -type DFF DFF
add mapped point reg_bank_inst/reg1[32]/q reg_bank_inst/reg1_reg[32]/Q -type DFF DFF
add mapped point reg_bank_inst/reg1[33]/q reg_bank_inst/reg1_reg[33]/Q -type DFF DFF
add mapped point reg_bank_inst/reg1[34]/q reg_bank_inst/reg1_reg[34]/Q -type DFF DFF
add mapped point reg_bank_inst/reg1[35]/q reg_bank_inst/reg1_reg[35]/Q -type DFF DFF
add mapped point reg_bank_inst/reg1[36]/q reg_bank_inst/reg1_reg[36]/Q -type DFF DFF
add mapped point reg_bank_inst/reg1[37]/q reg_bank_inst/reg1_reg[37]/Q -type DFF DFF
add mapped point reg_bank_inst/reg1[38]/q reg_bank_inst/reg1_reg[38]/Q -type DFF DFF
add mapped point reg_bank_inst/reg1[39]/q reg_bank_inst/reg1_reg[39]/Q -type DFF DFF
add mapped point reg_bank_inst/reg1[40]/q reg_bank_inst/reg1_reg[40]/Q -type DFF DFF
add mapped point reg_bank_inst/reg1[41]/q reg_bank_inst/reg1_reg[41]/Q -type DFF DFF
add mapped point reg_bank_inst/reg1[42]/q reg_bank_inst/reg1_reg[42]/Q -type DFF DFF
add mapped point reg_bank_inst/reg2[0]/q reg_bank_inst/reg2_reg[0]/Q -type DFF DFF
add mapped point reg_bank_inst/reg2[1]/q reg_bank_inst/reg2_reg[1]/Q -type DFF DFF
add mapped point reg_bank_inst/reg2[2]/q reg_bank_inst/reg2_reg[2]/Q -type DFF DFF
add mapped point reg_bank_inst/reg2[3]/q reg_bank_inst/reg2_reg[3]/Q -type DFF DFF
add mapped point reg_bank_inst/reg2[4]/q reg_bank_inst/reg2_reg[4]/Q -type DFF DFF
add mapped point reg_bank_inst/reg2[5]/q reg_bank_inst/reg2_reg[5]/Q -type DFF DFF
add mapped point reg_bank_inst/reg2[6]/q reg_bank_inst/reg2_reg[6]/Q -type DFF DFF
add mapped point reg_bank_inst/reg2[7]/q reg_bank_inst/reg2_reg[7]/Q -type DFF DFF
add mapped point reg_bank_inst/reg2[8]/q reg_bank_inst/reg2_reg[8]/Q -type DFF DFF
add mapped point reg_bank_inst/reg2[9]/q reg_bank_inst/reg2_reg[9]/Q -type DFF DFF
add mapped point reg_bank_inst/reg2[10]/q reg_bank_inst/reg2_reg[10]/Q -type DFF DFF
add mapped point reg_bank_inst/reg2[11]/q reg_bank_inst/reg2_reg[11]/Q -type DFF DFF
add mapped point reg_bank_inst/reg2[12]/q reg_bank_inst/reg2_reg[12]/Q -type DFF DFF
add mapped point reg_bank_inst/reg2[13]/q reg_bank_inst/reg2_reg[13]/Q -type DFF DFF
add mapped point reg_bank_inst/reg2[14]/q reg_bank_inst/reg2_reg[14]/Q -type DFF DFF
add mapped point reg_bank_inst/reg2[15]/q reg_bank_inst/reg2_reg[15]/Q -type DFF DFF
add mapped point reg_bank_inst/reg2[16]/q reg_bank_inst/reg2_reg[16]/Q -type DFF DFF
add mapped point reg_bank_inst/reg2[17]/q reg_bank_inst/reg2_reg[17]/Q -type DFF DFF
add mapped point reg_bank_inst/reg2[18]/q reg_bank_inst/reg2_reg[18]/Q -type DFF DFF
add mapped point reg_bank_inst/reg2[19]/q reg_bank_inst/reg2_reg[19]/Q -type DFF DFF
add mapped point reg_bank_inst/reg2[20]/q reg_bank_inst/reg2_reg[20]/Q -type DFF DFF
add mapped point reg_bank_inst/reg2[21]/q reg_bank_inst/reg2_reg[21]/Q -type DFF DFF
add mapped point reg_bank_inst/reg2[22]/q reg_bank_inst/reg2_reg[22]/Q -type DFF DFF
add mapped point reg_bank_inst/reg2[23]/q reg_bank_inst/reg2_reg[23]/Q -type DFF DFF
add mapped point reg_bank_inst/reg2[24]/q reg_bank_inst/reg2_reg[24]/Q -type DFF DFF
add mapped point reg_bank_inst/reg2[25]/q reg_bank_inst/reg2_reg[25]/Q -type DFF DFF
add mapped point reg_bank_inst/reg2[26]/q reg_bank_inst/reg2_reg[26]/Q -type DFF DFF
add mapped point reg_bank_inst/reg2[27]/q reg_bank_inst/reg2_reg[27]/Q -type DFF DFF
add mapped point reg_bank_inst/reg2[28]/q reg_bank_inst/reg2_reg[28]/Q -type DFF DFF
add mapped point reg_bank_inst/reg2[29]/q reg_bank_inst/reg2_reg[29]/Q -type DFF DFF
add mapped point reg_bank_inst/reg2[30]/q reg_bank_inst/reg2_reg[30]/Q -type DFF DFF
add mapped point reg_bank_inst/reg2[31]/q reg_bank_inst/reg2_reg[31]/Q -type DFF DFF
add mapped point reg_bank_inst/reg2[32]/q reg_bank_inst/reg2_reg[32]/Q -type DFF DFF
add mapped point reg_bank_inst/reg2[33]/q reg_bank_inst/reg2_reg[33]/Q -type DFF DFF
add mapped point reg_bank_inst/reg2[34]/q reg_bank_inst/reg2_reg[34]/Q -type DFF DFF
add mapped point reg_bank_inst/reg2[35]/q reg_bank_inst/reg2_reg[35]/Q -type DFF DFF
add mapped point reg_bank_inst/reg2[36]/q reg_bank_inst/reg2_reg[36]/Q -type DFF DFF
add mapped point reg_bank_inst/reg2[37]/q reg_bank_inst/reg2_reg[37]/Q -type DFF DFF
add mapped point reg_bank_inst/reg2[38]/q reg_bank_inst/reg2_reg[38]/Q -type DFF DFF
add mapped point reg_bank_inst/reg2[39]/q reg_bank_inst/reg2_reg[39]/Q -type DFF DFF
add mapped point reg_bank_inst/reg2[40]/q reg_bank_inst/reg2_reg[40]/Q -type DFF DFF
add mapped point reg_bank_inst/reg2[41]/q reg_bank_inst/reg2_reg[41]/Q -type DFF DFF
add mapped point reg_bank_inst/reg2[42]/q reg_bank_inst/reg2_reg[42]/Q -type DFF DFF
add mapped point reg_bank_inst/reg3[0]/q reg_bank_inst/reg3_reg[0]/Q -type DFF DFF
add mapped point reg_bank_inst/reg3[1]/q reg_bank_inst/reg3_reg[1]/Q -type DFF DFF
add mapped point reg_bank_inst/reg3[2]/q reg_bank_inst/reg3_reg[2]/Q -type DFF DFF
add mapped point reg_bank_inst/reg3[3]/q reg_bank_inst/reg3_reg[3]/Q -type DFF DFF
add mapped point reg_bank_inst/reg3[4]/q reg_bank_inst/reg3_reg[4]/Q -type DFF DFF
add mapped point reg_bank_inst/reg3[5]/q reg_bank_inst/reg3_reg[5]/Q -type DFF DFF
add mapped point reg_bank_inst/reg3[6]/q reg_bank_inst/reg3_reg[6]/Q -type DFF DFF
add mapped point reg_bank_inst/reg3[7]/q reg_bank_inst/reg3_reg[7]/Q -type DFF DFF
add mapped point reg_bank_inst/reg3[8]/q reg_bank_inst/reg3_reg[8]/Q -type DFF DFF
add mapped point reg_bank_inst/reg3[9]/q reg_bank_inst/reg3_reg[9]/Q -type DFF DFF
add mapped point reg_bank_inst/reg3[10]/q reg_bank_inst/reg3_reg[10]/Q -type DFF DFF
add mapped point reg_bank_inst/reg3[11]/q reg_bank_inst/reg3_reg[11]/Q -type DFF DFF
add mapped point reg_bank_inst/reg3[12]/q reg_bank_inst/reg3_reg[12]/Q -type DFF DFF
add mapped point reg_bank_inst/reg3[13]/q reg_bank_inst/reg3_reg[13]/Q -type DFF DFF
add mapped point reg_bank_inst/reg3[14]/q reg_bank_inst/reg3_reg[14]/Q -type DFF DFF
add mapped point reg_bank_inst/reg3[15]/q reg_bank_inst/reg3_reg[15]/Q -type DFF DFF
add mapped point reg_bank_inst/reg3[16]/q reg_bank_inst/reg3_reg[16]/Q -type DFF DFF
add mapped point reg_bank_inst/reg3[17]/q reg_bank_inst/reg3_reg[17]/Q -type DFF DFF
add mapped point reg_bank_inst/reg3[18]/q reg_bank_inst/reg3_reg[18]/Q -type DFF DFF
add mapped point reg_bank_inst/reg3[19]/q reg_bank_inst/reg3_reg[19]/Q -type DFF DFF
add mapped point reg_bank_inst/reg3[20]/q reg_bank_inst/reg3_reg[20]/Q -type DFF DFF
add mapped point reg_bank_inst/reg3[21]/q reg_bank_inst/reg3_reg[21]/Q -type DFF DFF
add mapped point reg_bank_inst/reg3[22]/q reg_bank_inst/reg3_reg[22]/Q -type DFF DFF
add mapped point reg_bank_inst/reg3[23]/q reg_bank_inst/reg3_reg[23]/Q -type DFF DFF
add mapped point reg_bank_inst/reg3[24]/q reg_bank_inst/reg3_reg[24]/Q -type DFF DFF
add mapped point reg_bank_inst/reg3[25]/q reg_bank_inst/reg3_reg[25]/Q -type DFF DFF
add mapped point reg_bank_inst/reg3[26]/q reg_bank_inst/reg3_reg[26]/Q -type DFF DFF
add mapped point reg_bank_inst/reg3[27]/q reg_bank_inst/reg3_reg[27]/Q -type DFF DFF
add mapped point reg_bank_inst/reg3[28]/q reg_bank_inst/reg3_reg[28]/Q -type DFF DFF
add mapped point reg_bank_inst/reg3[29]/q reg_bank_inst/reg3_reg[29]/Q -type DFF DFF
add mapped point reg_bank_inst/reg3[30]/q reg_bank_inst/reg3_reg[30]/Q -type DFF DFF
add mapped point reg_bank_inst/reg3[31]/q reg_bank_inst/reg3_reg[31]/Q -type DFF DFF
add mapped point reg_bank_inst/reg3[32]/q reg_bank_inst/reg3_reg[32]/Q -type DFF DFF
add mapped point reg_bank_inst/reg3[33]/q reg_bank_inst/reg3_reg[33]/Q -type DFF DFF
add mapped point reg_bank_inst/reg3[34]/q reg_bank_inst/reg3_reg[34]/Q -type DFF DFF
add mapped point reg_bank_inst/reg3[35]/q reg_bank_inst/reg3_reg[35]/Q -type DFF DFF
add mapped point reg_bank_inst/reg3[36]/q reg_bank_inst/reg3_reg[36]/Q -type DFF DFF
add mapped point reg_bank_inst/reg3[37]/q reg_bank_inst/reg3_reg[37]/Q -type DFF DFF
add mapped point reg_bank_inst/reg3[38]/q reg_bank_inst/reg3_reg[38]/Q -type DFF DFF
add mapped point reg_bank_inst/reg3[39]/q reg_bank_inst/reg3_reg[39]/Q -type DFF DFF
add mapped point reg_bank_inst/reg3[40]/q reg_bank_inst/reg3_reg[40]/Q -type DFF DFF
add mapped point reg_bank_inst/reg3[41]/q reg_bank_inst/reg3_reg[41]/Q -type DFF DFF
add mapped point reg_bank_inst/reg3[42]/q reg_bank_inst/reg3_reg[42]/Q -type DFF DFF
add mapped point spi_slave_inst/data[0]/q spi_slave_inst/data_reg[0]/Q -type DFF DFF
add mapped point spi_slave_inst/data[1]/q spi_slave_inst/data_reg[1]/Q -type DFF DFF
add mapped point spi_slave_inst/data[2]/q spi_slave_inst/data_reg[2]/Q -type DFF DFF
add mapped point spi_slave_inst/data[3]/q spi_slave_inst/data_reg[3]/Q -type DFF DFF
add mapped point spi_slave_inst/data[4]/q spi_slave_inst/data_reg[4]/Q -type DFF DFF
add mapped point spi_slave_inst/data[5]/q spi_slave_inst/data_reg[5]/Q -type DFF DFF
add mapped point spi_slave_inst/data[6]/q spi_slave_inst/data_reg[6]/Q -type DFF DFF
add mapped point spi_slave_inst/data[7]/q spi_slave_inst/data_reg[7]/Q -type DFF DFF
add mapped point spi_slave_inst/data[8]/q spi_slave_inst/data_reg[8]/Q -type DFF DFF
add mapped point spi_slave_inst/data[9]/q spi_slave_inst/data_reg[9]/Q -type DFF DFF
add mapped point spi_slave_inst/data[10]/q spi_slave_inst/data_reg[10]/Q -type DFF DFF
add mapped point spi_slave_inst/data[11]/q spi_slave_inst/data_reg[11]/Q -type DFF DFF
add mapped point spi_slave_inst/data[12]/q spi_slave_inst/data_reg[12]/Q -type DFF DFF
add mapped point spi_slave_inst/data[13]/q spi_slave_inst/data_reg[13]/Q -type DFF DFF
add mapped point spi_slave_inst/data[14]/q spi_slave_inst/data_reg[14]/Q -type DFF DFF
add mapped point spi_slave_inst/data[15]/q spi_slave_inst/data_reg[15]/Q -type DFF DFF
add mapped point spi_slave_inst/data_valid/q spi_slave_inst/data_valid_reg/Q -type DFF DFF
add mapped point spi_slave_inst/load_miso_data/q spi_slave_inst/load_miso_data_reg/Q -type DFF DFF
add mapped point spi_slave_inst/miso_bit_counter[0]/q spi_slave_inst/miso_bit_counter_reg[0]/Q -type DFF DFF
add mapped point spi_slave_inst/miso_bit_counter[1]/q spi_slave_inst/miso_bit_counter_reg[1]/Q -type DFF DFF
add mapped point spi_slave_inst/miso_bit_counter[2]/q spi_slave_inst/miso_bit_counter_reg[2]/Q -type DFF DFF
add mapped point spi_slave_inst/miso_bit_counter[3]/q spi_slave_inst/miso_bit_counter_reg[3]/Q -type DFF DFF
add mapped point spi_slave_inst/miso_bit_counter[4]/q spi_slave_inst/miso_bit_counter_reg[4]/Q -type DFF DFF
add mapped point spi_slave_inst/miso/q spi_slave_inst/miso_reg/Q -type DFF DFF
add mapped point spi_slave_inst/miso_shift_reg[0]/q spi_slave_inst/miso_shift_reg_reg[0]/Q -type DFF DFF
add mapped point spi_slave_inst/miso_shift_reg[1]/q spi_slave_inst/miso_shift_reg_reg[1]/Q -type DFF DFF
add mapped point spi_slave_inst/miso_shift_reg[2]/q spi_slave_inst/miso_shift_reg_reg[2]/Q -type DFF DFF
add mapped point spi_slave_inst/miso_shift_reg[3]/q spi_slave_inst/miso_shift_reg_reg[3]/Q -type DFF DFF
add mapped point spi_slave_inst/miso_shift_reg[4]/q spi_slave_inst/miso_shift_reg_reg[4]/Q -type DFF DFF
add mapped point spi_slave_inst/miso_shift_reg[5]/q spi_slave_inst/miso_shift_reg_reg[5]/Q -type DFF DFF
add mapped point spi_slave_inst/miso_shift_reg[6]/q spi_slave_inst/miso_shift_reg_reg[6]/Q -type DFF DFF
add mapped point spi_slave_inst/miso_shift_reg[7]/q spi_slave_inst/miso_shift_reg_reg[7]/Q -type DFF DFF
add mapped point spi_slave_inst/miso_shift_reg[8]/q spi_slave_inst/miso_shift_reg_reg[8]/Q -type DFF DFF
add mapped point spi_slave_inst/miso_shift_reg[9]/q spi_slave_inst/miso_shift_reg_reg[9]/Q -type DFF DFF
add mapped point spi_slave_inst/miso_shift_reg[10]/q spi_slave_inst/miso_shift_reg_reg[10]/Q -type DFF DFF
add mapped point spi_slave_inst/miso_shift_reg[11]/q spi_slave_inst/miso_shift_reg_reg[11]/Q -type DFF DFF
add mapped point spi_slave_inst/miso_shift_reg[12]/q spi_slave_inst/miso_shift_reg_reg[12]/Q -type DFF DFF
add mapped point spi_slave_inst/miso_shift_reg[13]/q spi_slave_inst/miso_shift_reg_reg[13]/Q -type DFF DFF
add mapped point spi_slave_inst/miso_shift_reg[14]/q spi_slave_inst/miso_shift_reg_reg[14]/Q -type DFF DFF
add mapped point spi_slave_inst/miso_shift_reg[15]/q spi_slave_inst/miso_shift_reg_reg[15]/Q -type DFF DFF
add mapped point spi_slave_inst/mosi_bit_counter[0]/q spi_slave_inst/mosi_bit_counter_reg[0]/Q -type DFF DFF
add mapped point spi_slave_inst/mosi_bit_counter[1]/q spi_slave_inst/mosi_bit_counter_reg[1]/Q -type DFF DFF
add mapped point spi_slave_inst/mosi_bit_counter[2]/q spi_slave_inst/mosi_bit_counter_reg[2]/Q -type DFF DFF
add mapped point spi_slave_inst/mosi_bit_counter[3]/q spi_slave_inst/mosi_bit_counter_reg[3]/Q -type DFF DFF
add mapped point spi_slave_inst/mosi_bit_counter[4]/q spi_slave_inst/mosi_bit_counter_reg[4]/Q -type DFF DFF
add mapped point spi_slave_inst/mosi_shift_reg[0]/q spi_slave_inst/mosi_shift_reg_reg[0]/Q -type DFF DFF
add mapped point spi_slave_inst/mosi_shift_reg[1]/q spi_slave_inst/mosi_shift_reg_reg[1]/Q -type DFF DFF
add mapped point spi_slave_inst/mosi_shift_reg[2]/q spi_slave_inst/mosi_shift_reg_reg[2]/Q -type DFF DFF
add mapped point spi_slave_inst/mosi_shift_reg[3]/q spi_slave_inst/mosi_shift_reg_reg[3]/Q -type DFF DFF
add mapped point spi_slave_inst/mosi_shift_reg[4]/q spi_slave_inst/mosi_shift_reg_reg[4]/Q -type DFF DFF
add mapped point spi_slave_inst/mosi_shift_reg[5]/q spi_slave_inst/mosi_shift_reg_reg[5]/Q -type DFF DFF
add mapped point spi_slave_inst/mosi_shift_reg[6]/q spi_slave_inst/mosi_shift_reg_reg[6]/Q -type DFF DFF
add mapped point spi_slave_inst/mosi_shift_reg[7]/q spi_slave_inst/mosi_shift_reg_reg[7]/Q -type DFF DFF
add mapped point spi_slave_inst/mosi_shift_reg[8]/q spi_slave_inst/mosi_shift_reg_reg[8]/Q -type DFF DFF
add mapped point spi_slave_inst/mosi_shift_reg[9]/q spi_slave_inst/mosi_shift_reg_reg[9]/Q -type DFF DFF
add mapped point spi_slave_inst/mosi_shift_reg[10]/q spi_slave_inst/mosi_shift_reg_reg[10]/Q -type DFF DFF
add mapped point spi_slave_inst/mosi_shift_reg[11]/q spi_slave_inst/mosi_shift_reg_reg[11]/Q -type DFF DFF
add mapped point spi_slave_inst/mosi_shift_reg[12]/q spi_slave_inst/mosi_shift_reg_reg[12]/Q -type DFF DFF
add mapped point spi_slave_inst/mosi_shift_reg[13]/q spi_slave_inst/mosi_shift_reg_reg[13]/Q -type DFF DFF
add mapped point spi_slave_inst/mosi_shift_reg[14]/q spi_slave_inst/mosi_shift_reg_reg[14]/Q -type DFF DFF
add mapped point spi_slave_inst/mosi_shift_reg[15]/q spi_slave_inst/mosi_shift_reg_reg[15]/Q -type DFF DFF
add mapped point read_address[1]/q read_address_reg[1]/Q -type DFF DFF
add mapped point read_address[0]/q read_address_reg[0]/Q -type DFF DFF
add mapped point fifo_write_enable/q fifo_write_enable_reg/Q -type DFF DFF
add mapped point fifo_data_valid_prev/q fifo_data_valid_prev_reg/Q -type DFF DFF
add mapped point assembler_data_valid_prev/q assembler_data_valid_prev_reg/Q -type DFF DFF
add mapped point control[0]/q control_reg[0]/Q -type DFF DFF
add mapped point control[1]/q control_reg[1]/Q -type DFF DFF
add mapped point read_enable/q read_enable_reg/Q -type DFF DFF
add mapped point enable_continuous_output/q enable_continuous_output_reg/Q -type DFF DFF
add mapped point write_enable/q write_enable_reg/Q -type DFF DFF
add mapped point spi_valid_prev/q spi_valid_prev_reg/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
